server:
  port: 7000

spring:
  application:
    name: pro-jet-center


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}
  server:
    wait-time-in-ms-when-sync-empty: 0
