server:
  port: 7000

spring:
  application:
    name: pro-jet-center
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    wait-time-in-ms-when-sync-empty: 0
